export const env = {
  dbURI: process.env.DB_URI,
  nodeEnv: process.env.NODE_ENV,
  port: process.env.PORT,
  accessTokenSecret: process.env.ACCESS_TOKEN_SECRET,
  accessTokenExpiry: process.env.ACCESS_TOKEN_EXPIRY,
  refreshTokenSecret: process.env.REFRESH_TOKEN_SECRET,
  refreshTokenExpiry: process.env.REFRESH_TOKEN_EXPIRY,
  origin: process.env.ORIGIN,
  emailUsername: process.env.EMAIL_USER,
  emailPassword: process.env.EMAIL_PASS,
  senderEmailAddress: process.env.SENDER_EMAIL_ADDRESS,
  smtpHost: process.env.SMTP_HOST,
  smtpPort: process.env.SMTP_PORT,
  redisClientURL: process.env.REDIS_CLIENT_URL,
};
